# Font style metadata
name = "Default"

# Optional Google font URL
google_fonts = "family=Rubik:wght@400;700&family=Roboto+Mono&family=Roboto:wght@400;700"

# Font families
heading_font = "Rubik"
body_font = "Roboto"
nav_font = "Roboto"
mono_font = "Roboto Mono"